services:
  telegram_utils_bot:
    container_name: telegram_utils_bot
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
    env_file:
      - .env
    volumes:
      - ./:/code/app
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  bgutil-provider:
    container_name: bgutil-provider
    image: brainicism/bgutil-ytdlp-pot-provider
    ports:
      - "127.0.0.1:4416:4416"
    restart: unless-stopped
